Repository SOPTerest/SOPTerest-Client, pull requests merged in 2022-05, with the labels that each got.

#3 디자인 시스템 세팅하기
  public/index.html
  src/styles/color.ts
  src/styles/fonts/font.ts
Labels: chore 🪙

#4 라우터 파일 설정
  package.json
  src/App.tsx
  src/pages/Pin.tsx
  src/pages/PinDetail.tsx
  src/pages/PinEdit.tsx
  src/router.tsx
  yarn.lock
Labels: chore 🪙

#7 board 컴포넌트 만들기
  package-lock.json
  src/components/BoardItem.tsx
  src/components/BoardList.tsx
  src/pages/Pin.tsx
  src/styles/color.ts
  src/types/index.ts
Labels: feature 🚘

#9 chore: 라우터 변경 내용 반영
  src/pages/Board.tsx
  src/pages/BoardForm.tsx
  src/pages/MyPage.tsx
  src/pages/PinDetail.tsx
  src/pages/PinEdit.tsx
  src/router.tsx
Labels: chore 🪙

#13 마이페이지 상단 헤더 추가
  src/assets/icons/icon_back.svg
  src/assets/icons/icon_cancel.svg
  src/assets/icons/icon_ideamore.svg
  src/assets/icons/icon_organize.svg
  src/assets/icons/icon_plus.svg
  src/assets/icons/icon_search.svg
  src/assets/icons/icon_setting.svg
  src/assets/icons/icon_viewmore.svg
  src/assets/icons/index.ts
  src/components/MyPageHeader.tsx
  src/pages/MyPage.tsx
Labels: feature 🚘

#16 마이페이지 유저 정보 컴포넌트 만들기
  src/components/BoardItem.tsx
  src/components/BoardList.tsx
  src/components/MyPageHeader.tsx
  src/pages/MyPage.tsx
  src/styles/font.ts
Labels: feature 🚘

#19 마이페이지 네비게이션 구현
  src/assets/icons/icon_chat.svg
  src/assets/icons/icon_home.svg
  src/assets/icons/icon_plus_gray_1.svg
  src/assets/icons/icon_search_gray_1.svg
  src/assets/icons/index.ts
  src/components/MyPageNavigation.tsx
  src/pages/MyPage.tsx
Labels: feature 🚘

#21 보드 페이지 퍼블리싱
  src/App.tsx
  src/assets/icons/index.ts
  src/components/Router.tsx
  src/pages/Board.tsx
  src/services/mock/data.ts
  src/styles/global.ts
Labels: chore 🪙, layout 🐳

#17 바텀 시트 컴포넌트 추가
  .gitignore
  src/components/BottomSheet.tsx
  src/pages/MyPage.tsx
  src/styles/font.ts
Labels: feature 🚘, chore 🪙

#23 보드 생성 컴포넌트 추가
  src/components/BoardFormToast.tsx
  src/pages/BoardForm.tsx
Labels: feature 🚘

#25 리드미 작성하기
  README.md
Labels: documentation 🐦

#27 마이페이지 네비게이션 플러스 버튼 클릭 이벤트 부착
  src/assets/icons/index.ts
  src/components/BottomSheet.tsx
  src/components/MyPageNavigation.tsx
  src/pages/BoardForm.tsx
  src/pages/MyPage.tsx
  yarn.lock
Labels: feature 🚘

#28 토스트 굽기
  package.json
  src/App.tsx
  src/assets/icons/icon_blue_check.svg
  src/assets/icons/index.ts
  src/components/common/Toast.tsx
  src/hooks/useToast.ts
  src/pages/Board.tsx
  src/stores/index.ts
  src/types/index.ts
  yarn.lock
Labels: feature 🚘, layout 🐳

#31 데이터 프로바이더 만들고 보드 조회에 적용
  package.json
  src/assets/icons/index.ts
  src/pages/Board.tsx
  src/services/index.ts
  src/services/mock/index.ts
  src/services/remote/base.ts
  src/services/remote/index.ts
  src/utils/time.ts
  yarn.lock
Labels: feature 🚘
